"""empty message

Revision ID: 974b93e9972d
Revises: de90cdef0218
Create Date: 2023-11-16 10:14:31.259480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974b93e9972d'
down_revision = 'de90cdef0218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.String(length=150), nullable=False))
        batch_op.drop_column('team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('team_name')

    # ### end Alembic commands ###
